version: '3'

services:
  app:
    restart: always
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - app_volume:/home/node/app
    depends_on:
      - redis
      - mongo
      - rabbitmq

  redis:
    image: redis/redis-stack-server:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_volume:/data:rw
    environment:
      # referance: https://stackoverflow.com/a/76482901
      - REDIS_ARGS=--save 10 1 --appendonly yes --requirepass redis_password --user redis_username on >redis_password ~* allcommands --user default off nopass nocommands

  mongo:
    image: mongodb/mongodb-community-server:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_volume:/data/db
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=mongo_username
      - MONGODB_INITDB_ROOT_PASSWORD=mongo_password

  rabbitmq:
    image: rabbitmq:3.12.13-management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq/mnesia
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq_username
      - RABBITMQ_DEFAULT_PASS=rabbitmq_password

volumes:
  app_volume:
  redis_volume:
  mongo_volume:
  rabbitmq_volume: