version: '3'

services:
  app:
    restart: always
    build:
      context: .
    environment:
      NODE_ENV: production
      PORT: 3000
      SESSION_MS_URI: host.docker.internal:20000
      QUEUE_MS_URI: host.docker.internal:20001
      USER_MS_URI: host.docker.internal:20002
      FILE_MS_URI: host.docker.internal:20003
      HMAC_SECRET: rmR6aiKelvDnIqIp2rUtwsBmD8ZbtjPrg4i1dJLYoDetXPbX4Vh0O8kChcD6OTfZXLh_NjOHU7ob-lA40CKudbDwXWEH5BZ7_saixeS3foxDuzvU3uskS84JdU5vmzI61TGZso_Wd6OIQH5H8gg7HFJmqbMlqCIuavqjqC-Li7M
      JWT_SECRET: wrL3EZegwtbbKXQKrlq7MW0HD_d3y7bn_wNm3O6xHSfF2ywB5cPM6fkJSkSufSXsOwFr_irtRZmqTJrKIwjGZvExYVy_ewBeaJe9S2h505sYsHwl0maNEngAdEUm4D9mY7b6j3ipjtrj7wsd8BwpKrpPcoHXTjeQLMcYBdbVqtY
    ports:
      - 3000:3000
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - cdn_volume://home/node/app/upload
    networks:
      - cdn

networks:
  cdn:

volumes:
  cdn_volume:
